package controller;

/**
 * Created by tmonn on 30.06.2017.
 */
public enum ETabController {
    ENVIRONMENT_CONTROLLER,
    FUNCTIONAL_REQUIREMENTS_CONTROLLER,
    PRODUCT_DATA_CONTROLLER,
    PRODUCT_USE_CONTROLLER,
    TARGET_SPECIFICATION_CONTROLLER,
    ESTIMATION_CONFIGURATION_CONTROLLER,
    COST_ESTIMATION_CONTROLLER
}
